name: provision

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on: 
  push:
    paths:
    - Deploy/arm/**
    - .github/workflows/provision-resources.yml
    branches:
      - master 

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # connect to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Provisions resources using ARM template
    - name: Provision Azure resources
      run: |       
        az account set -s ${{ secrets.AZURE_SUBSCRIPTION }}              
        az deployment group create -g rpsls --template-file "Deploy/arm/deployment.json" --parameters servicePrincipalId=${{ secrets.AZURE_CLIENT_ID }} --parameters servicePrincipalSecret=${{ secrets.AZURE_CLIENT_PWD }} --parameters aksVersion="1.17.3" --parameters kv_objectId="b4e21852-bf98-41cd-b2fe-136466e0b4f1" --parameters funcAppSkuName="Y1" --parameters funcAppSkuTier="Dynamic"


   
