name: provision

# Controls when the action will run. Triggers the workflow on push or PR
# events but only for the master branch
on: 
  push:
    paths:
    - Deploy/arm/**
    - .github/workflows/provision-resources.yml
    branches:
      - master 

jobs:
  provision:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # connect to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Provions resources using arm template
    - name: provision Azure resources
      run: |

        $resourceGroup="rpslsuat"
        Write-Host "Begining the ARM deployment..." -ForegroundColor Yellow
        
        az account set -s ${{ secrets.AZURE_SUBSCRIPTION }}
        $objectId = $(az ad sp show --id $clientId --query "objectId" -o tsv)

        $rg = $(az group create -n $resourceGroup -l $location -o json | ConvertFrom-Json)
        $location = $rg.location

        $aksVersions=$(az aks get-versions -l $location --query  orchestrators[].orchestratorVersion -o json | ConvertFrom-Json)
        $aksVersion=$aksVersions[$aksVersions.Length-1]
        Write-Host "AKS last version is $aksVersion. Will use that" -ForegroundColor Yellow
        
        $funcSvcPlan="Y1"
        funcSvcPlanTier="Dynamic"

        az group deployment create -g $resourceGroup --template-file "Deploy/arm/deployment.json" --parameters servicePrincipalId=${{ secrets.AZURE_CLIENT_ID }} --parameters servicePrincipalSecret=${{ secrets.AZURE_CLIENT_PWD }} --parameters aksVersion=$aksVersion --parameters kv_objectId=$objectId --parameters funcAppSkuName=$funcSvcPlan --parameters funcAppSkuTier=$funcSvcPlanTier

        exit $LastExitCode
        
        # Deploy/powershell/Deploy-Arm-Azure.ps1 -resourceGroup rpslsuat -clientId ${{ secrets.AZURE_CLIENT_ID }} -password ${{ secrets.AZURE_CLIENT_PWD }} -location westus2
   

   
