name: provision

# Controls when the action will run. Triggers the workflow on push or PR
# events but only for the master branch
on: 
  push:
    paths:
    - Deploy/arm/**
    - .github/workflows/provision-resources.yml
    branches:
      - master 

jobs:
  provision:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # connect to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set Azure subscription
      run: |
        az account set -s ${{ secrets.AZURE_SUBSCRIPTION }}
    # Provions resources using arm templates
    - name: provision Azure resources
      run: |
        $resourceGroup="rpslsuat"
        Write-Host "Begining the ARM deployment..." -ForegroundColor Yellow
        $objectId = $(az ad sp show --id $clientId --query "objectId" -o tsv)
        
        az group deployment create -g $resourceGroup --template-file "Deploy/arm/deployment.json" --parameters servicePrincipalId=${{ secrets.AZURE_CLIENT_ID }} --parameters servicePrincipalSecret=${{ secrets.AZURE_CLIENT_PWD }} --parameters kv_objectId=$objectId 

        exit $LastExitCode
        
        # Deploy/powershell/Deploy-Arm-Azure.ps1 -resourceGroup rpslsuat -clientId ${{ secrets.AZURE_CLIENT_ID }} -password ${{ secrets.AZURE_CLIENT_PWD }} -location westus2
   
