name: provision

# Controls when the action will run. Triggers the workflow on push or PR
# events but only for the master branch
on: 
  push:
    paths:
    - Deploy/arm/**
    - .github/workflows/provision-resources.yml
    branches:
      - master 

jobs:
  provision:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # connect to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Provions resources using arm template
    - name: provision Azure resources
      env:
        RG_NAME: "rpslsuat"
        CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        PWD: ${{ secrets.AZURE_CLIENT_PWD }}
        FUNC_SVC_PLAN: Y1
        FUNC_SVC_TIER: Dynamic
        LOCATION: westus2
        AZURE_SUB: ${{ secrets.AZURE_SUBSCRIPTION }}
      run: |   
        Write-Host "Begining the ARM deployment..." -ForegroundColor Yellow
        Write-Host $CLIENT_ID $RG_NAME $PWD $FUNC_SVC_PLAN $FUNC_SVC_TIER $LOCATION $AZURE_SUB
        
        az account set -s $AZURE_SUB
        
        $objectId = $(az ad sp show --id $CLIENT_ID --query "objectId" -o tsv)
        Write-Host $objectId
        
        $rg = $(az group create -n $RG_NAME -l $LOCATION -o json | ConvertFrom-Json)
        $location = $rg.location
        Write-Host $location
        
        $aksVersions=$(az aks get-versions -l $LOCATION --query  orchestrators[].orchestratorVersion -o json | ConvertFrom-Json)
        $aksVersion=$aksVersions[$aksVersions.Length-1]
        Write-Host $aksVersion
        
        az group deployment create -g $RG_NAME --template-file "Deploy/arm/deployment.json" --parameters servicePrincipalId=$CLIENT_ID --parameters servicePrincipalSecret=$PWD --parameters aksVersion=$aksVersion --parameters kv_objectId=$objectId --parameters funcAppSkuName=$FUNC_SVC_PLAN --parameters funcAppSkuTier=$FUNC_SVC_TIER
        
        exit $LastExitCode
        
        # Deploy/powershell/Deploy-Arm-Azure.ps1 -resourceGroup rpslsuat -clientId ${{ secrets.AZURE_CLIENT_ID }} -password ${{ secrets.AZURE_CLIENT_PWD }} -location westus2



   
