name: provision

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    paths:
    - Deploy/arm/**
    - .github/workflows/provision-resources.yml
    branches:
      - master 

jobs:
  provision:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: provision Azure resources
      run: |
        Deploy/powershell/Deploy-Arm-Azure.ps1 -resourceGroup rpsls265 -clientId ${{ secrets.AZURE_CLIENT_ID }} -password ${{ secrets.AZURE_CLIENT_PWD }} location eastus2
   
